-- MySQL Script generated by MySQL Workbench
-- Sun Sep 22 21:01:33 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema swgama
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `swgama` ;

-- -----------------------------------------------------
-- Schema swgama
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `swgama` DEFAULT CHARACTER SET utf8 ;
USE `swgama` ;

-- -----------------------------------------------------
-- Table `swgama`.`tbFuncionario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `swgama`.`tbFuncionario` ;

CREATE TABLE IF NOT EXISTS `swgama`.`tbFuncionario` (
  `idFuncionario` INT NOT NULL AUTO_INCREMENT COMMENT 'Código do funcionário. Validação: >0.',
  `nmFuncionario` VARCHAR(100) NOT NULL COMMENT 'Nome do funcionário. Validação: número de caracteres > 3.',
  `cpf` VARCHAR(11) NOT NULL COMMENT 'CPF do funcionário. Validação: número de caracteres = 11.',
  `telefone` VARCHAR(11) NOT NULL COMMENT 'Telefone do funcionário. Validação: número de caracteres = 11. Máscara: (99)9999-9999.',
  `dtNasc` DATE NOT NULL COMMENT 'Data de nascimento do funcionário. Validação: ser uma data válida.',
  `sexo` VARCHAR(1) NULL COMMENT 'Sexo do funcionário. Validação: número de caracter = 1. Domínio: F ou M.\n',
  `email` VARCHAR(90) NULL COMMENT 'Email do funcionário. Validação: número de caracteres >= 3.',
  `salario` DOUBLE NOT NULL COMMENT 'Salário do funcionário. Validação: quantidade de números 8,2.',
  `dtPagamento` DATE NULL COMMENT 'Data de pagamento do salário.',
  `endereco` VARCHAR(250) NOT NULL COMMENT 'Endereço do funcionário. Validação: número de caracteres >= 3.',
  `senha` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idFuncionario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `swgama`.`tbGola`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `swgama`.`tbGola` ;

CREATE TABLE IF NOT EXISTS `swgama`.`tbGola` (
  `idGola` INT NOT NULL AUTO_INCREMENT COMMENT 'Código da gola. Validação: >0.\n',
  `nmGola` VARCHAR(50) NOT NULL COMMENT 'Nome da gola. Validação: número de caracteres >= 3.',
  PRIMARY KEY (`idGola`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `swgama`.`tbMalha`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `swgama`.`tbMalha` ;

CREATE TABLE IF NOT EXISTS `swgama`.`tbMalha` (
  `idMalha` INT NOT NULL AUTO_INCREMENT COMMENT 'Código do tipo de malha. Validação: >0.',
  `nmMalha` VARCHAR(50) NOT NULL COMMENT 'Nome do tipo de malha, exemplo: poliéster. Validação: número de caracteres >= 3.',
  PRIMARY KEY (`idMalha`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `swgama`.`tbTamanho`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `swgama`.`tbTamanho` ;

CREATE TABLE IF NOT EXISTS `swgama`.`tbTamanho` (
  `idTamanho` INT NOT NULL AUTO_INCREMENT COMMENT 'Código do tamanho da blusa. Validação: >0.',
  `tamanho` VARCHAR(10) NOT NULL COMMENT 'Nome do tamanho da blusa. Validação: número de caracteres >= 3.',
  `altura` DOUBLE NOT NULL COMMENT 'Valor da altura da blusa. Validação: > 0. Máscara: 99.999.',
  `largura` DOUBLE NOT NULL COMMENT 'Valor da largura da blusa. Validação: > 0. Máscara: 99.999.',
  PRIMARY KEY (`idTamanho`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `swgama`.`tbModoProd`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `swgama`.`tbModoProd` ;

CREATE TABLE IF NOT EXISTS `swgama`.`tbModoProd` (
  `idModoProd` INT NOT NULL AUTO_INCREMENT COMMENT 'Código do modo de produção. Validação: >0.\n',
  `nmModoProd` VARCHAR(50) NOT NULL COMMENT 'Nome do modo de produção, exemplo: silk ou sublimação. Validação: número de caracteres >= 3.',
  PRIMARY KEY (`idModoProd`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `swgama`.`tbArte`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `swgama`.`tbArte` ;

CREATE TABLE IF NOT EXISTS `swgama`.`tbArte` (
  `idArte` INT NOT NULL,
  `nmArte` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idArte`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `swgama`.`tbBlusa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `swgama`.`tbBlusa` ;

CREATE TABLE IF NOT EXISTS `swgama`.`tbBlusa` (
  `idBlusa` INT NOT NULL AUTO_INCREMENT COMMENT 'Código da blusa. Validação: >0.',
  `nome` VARCHAR(45) NULL,
  `valor` DOUBLE NULL COMMENT 'Valor unitário pago pela blusa. Validação: >0. Máscara: R$00,00.',
  `qtdEstoque` INT NULL COMMENT 'Quantidade dessa blusa. Validação: >0. Máscara: 99.999',
  `status` VARCHAR(20) NOT NULL,
  `idGola` INT NOT NULL,
  `idMalha` INT NOT NULL,
  `idTamanho` INT NOT NULL,
  `idModoProd` INT NOT NULL,
  `idArte` INT NULL,
  PRIMARY KEY (`idBlusa`),
  INDEX `fk_tbBlusa_tbGola1_idx` (`idGola` ASC) ,
  INDEX `fk_tbBlusa_tbMalha1_idx` (`idMalha` ASC) ,
  INDEX `fk_tbBlusa_tbTamanho1_idx` (`idTamanho` ASC) ,
  INDEX `fk_tbBlusa_tbModoProd1_idx` (`idModoProd` ASC) ,
  INDEX `fk_tbBlusa_tbArte1_idx` (`idArte` ASC) ,
  CONSTRAINT `fk_tbBlusa_tbGola1`
    FOREIGN KEY (`idGola`)
    REFERENCES `swgama`.`tbGola` (`idGola`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbBlusa_tbMalha1`
    FOREIGN KEY (`idMalha`)
    REFERENCES `swgama`.`tbMalha` (`idMalha`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbBlusa_tbTamanho1`
    FOREIGN KEY (`idTamanho`)
    REFERENCES `swgama`.`tbTamanho` (`idTamanho`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbBlusa_tbModoProd1`
    FOREIGN KEY (`idModoProd`)
    REFERENCES `swgama`.`tbModoProd` (`idModoProd`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbBlusa_tbArte1`
    FOREIGN KEY (`idArte`)
    REFERENCES `swgama`.`tbArte` (`idArte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `swgama`.`tbModelo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `swgama`.`tbModelo` ;

CREATE TABLE IF NOT EXISTS `swgama`.`tbModelo` (
  `idModelo` INT NOT NULL AUTO_INCREMENT COMMENT 'Código do modelo de blusas. Validação: >0.',
  `nmModelo` VARCHAR(50) NOT NULL COMMENT 'Nome do modelo. Validação: número de caracteres >= 3.',
  `imagem` VARCHAR(200) NOT NULL COMMENT 'Caminho da imagem do modelo de blusa.',
  `idBlusa` INT NOT NULL COMMENT 'Código estrangeiro de uma blusa que representa o modelo. Validação: >0',
  PRIMARY KEY (`idModelo`),
  INDEX `fk_tbModelo_tbBlusa1_idx` (`idBlusa` ASC) ,
  CONSTRAINT `fk_tbModelo_tbBlusa1`
    FOREIGN KEY (`idBlusa`)
    REFERENCES `swgama`.`tbBlusa` (`idBlusa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `swgama`.`tbCliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `swgama`.`tbCliente` ;

CREATE TABLE IF NOT EXISTS `swgama`.`tbCliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT COMMENT 'Chave primária da tabela cliente.\n',
  `nmCliente` VARCHAR(100) NOT NULL COMMENT 'Nome do cliente. Validação: número de caracteres >= 3.\n',
  `dtNasc` DATE NOT NULL COMMENT 'Data de nascimento do cliente. Máscara: 00/00/0000. Validação: < dataAtual.\n',
  `telefone` VARCHAR(11) NOT NULL COMMENT 'Telefone do cliente. Máscara: (00)00000-0000.\n',
  `email` VARCHAR(90) NOT NULL COMMENT ' Email do cliente. Máscara: joão@gmail.com\n',
  `cpf` VARCHAR(11) NULL COMMENT 'CPF do cliente. Máscara: 000.000.000-00. Validação: CPF válido',
  `cnpj` VARCHAR(14) NULL COMMENT 'CNPJ do cliente. Máscara: 99.999.999/9999-99. Validação: CNPJ válido',
  `tipo` VARCHAR(10) NOT NULL COMMENT 'Tipo do cliente. Validação: número de caracteres >= 3.\n',
  `endereco` VARCHAR(200) NOT NULL COMMENT 'Endereço do cliente. Validação: número de caracteres >= 3.\n',
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `swgama`.`tbVenda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `swgama`.`tbVenda` (
  `idVenda` INT NOT NULL AUTO_INCREMENT COMMENT 'Código da venda. Validação: >0.',
  `dataHora` DATE NOT NULL COMMENT 'Data que foi realizada a venda. ',
  `valorTotal` DOUBLE NOT NULL COMMENT 'Valor total do venda. Validação: >0. Máscara: R$00,00.',
  `idCliente` INT NULL COMMENT 'Código estrangeiro do cliente que realizou o venda. Validação: >0.',
  `desconto` DOUBLE NULL,
  `observacao` VARCHAR(100) NULL,
  `tipo` VARCHAR(20) NULL,
  PRIMARY KEY (`idVenda`),
  INDEX `fk_tbVenda_tbCliente1_idx` (`idCliente` ASC) ,
  CONSTRAINT `fk_tbVenda_tbCliente1`
    FOREIGN KEY (`idCliente`)
    REFERENCES `swgama`.`tbCliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `swgama`.`tbFornecedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `swgama`.`tbFornecedor` ;

CREATE TABLE IF NOT EXISTS `swgama`.`tbFornecedor` (
  `idFornecedor` INT NOT NULL AUTO_INCREMENT COMMENT 'Chave primária da tabela fornecedor.\n',
  `nmFornecedor` VARCHAR(100) NOT NULL COMMENT 'Nome do fornecedor. Validação: número de caracteres >= 3.\n',
  `telefone` VARCHAR(11) NULL COMMENT 'Nome do fornecedor. Validação: número de caracteres >= 3.\n',
  `email` VARCHAR(90) NULL COMMENT ' Email do fornecedor. Máscara: joão@gmail.com',
  `endereco` VARCHAR(200) NULL COMMENT 'Endereço do forncedor. Validação: número de caracteres >= 3.\n',
  PRIMARY KEY (`idFornecedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `swgama`.`tbInsumo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `swgama`.`tbInsumo` ;

CREATE TABLE IF NOT EXISTS `swgama`.`tbInsumo` (
  `idInsumo` INT NOT NULL AUTO_INCREMENT COMMENT 'Chave primária da tabela insumo.\n',
  `nmInsumo` VARCHAR(50) NOT NULL COMMENT 'Nome do insumo. Validação: número de caracteres >= 3.\n',
  `qtdMin` INT NOT NULL COMMENT 'Quantidade mínima desejada do insumo. Validação: >= 0.',
  `qtdEstoque` INT NOT NULL COMMENT 'Quantidade do insumo em estoque. Validação: >= 0.\n',
  `descricao` VARCHAR(45) NULL,
  PRIMARY KEY (`idInsumo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `swgama`.`tbDespesa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `swgama`.`tbDespesa` ;

CREATE TABLE IF NOT EXISTS `swgama`.`tbDespesa` (
  `idDespesa` INT NOT NULL AUTO_INCREMENT COMMENT 'Chave primária da tabela despesa.',
  `nmDespesa` VARCHAR(50) NOT NULL COMMENT 'Nome da despesa. Validação: número de caracteres >= 3.\n',
  PRIMARY KEY (`idDespesa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `swgama`.`tbEstoque`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `swgama`.`tbEstoque` ;

CREATE TABLE IF NOT EXISTS `swgama`.`tbEstoque` (
  `idEstoque` INT NOT NULL AUTO_INCREMENT COMMENT 'Código do estoque. Validação: >0.',
  `tipo` VARCHAR(45) NOT NULL COMMENT 'Tipo da transação do estoque: entrada ou saída. Validação: número de caracters >=3. Valores: ENTRADA, SAIDA, SAIDALOJA.',
  `data` DATE NOT NULL COMMENT 'Data a qual refere-se a transação de estoque.',
  PRIMARY KEY (`idEstoque`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `swgama`.`tbCalendario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `swgama`.`tbCalendario` ;

CREATE TABLE IF NOT EXISTS `swgama`.`tbCalendario` (
  `idCalendario` INT NOT NULL AUTO_INCREMENT COMMENT 'Chave primária da tabela calendário.\n',
  `titulo` VARCHAR(200) NOT NULL COMMENT 'Nome do evento. Validação: número de caracteres >= 3.',
  `dtEvento` DATE NOT NULL COMMENT 'Data do evento. Máscara: 00/00/0000.',
  PRIMARY KEY (`idCalendario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `swgama`.`tbBlusa_tbVenda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `swgama`.`tbBlusa_tbVenda` (
  `idBlusaVenda` INT NOT NULL AUTO_INCREMENT,
  `idBlusa` INT NOT NULL COMMENT 'Códiog estrangeiro e primário da blusa. Validação: >0.',
  `idVenda` INT NOT NULL COMMENT 'Código estrangeiro e primário do venda da blusa. Validação: > 0.',
  `valor` DOUBLE NULL,
  `qtd` INT NOT NULL,
  `observacao` VARCHAR(200) NULL,
  PRIMARY KEY (`idBlusaVenda`),
  INDEX `fk_tbBlusa_has_tbVenda_tbVenda1_idx` (`idVenda` ASC) ,
  INDEX `fk_tbBlusa_has_tbVenda_tbBlusa1_idx` (`idBlusa` ASC) ,
  CONSTRAINT `fk_tbBlusa_has_tbVenda_tbBlusa1`
    FOREIGN KEY (`idBlusa`)
    REFERENCES `swgama`.`tbBlusa` (`idBlusa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbBlusa_has_tbVenda_tbVenda1`
    FOREIGN KEY (`idVenda`)
    REFERENCES `swgama`.`tbVenda` (`idVenda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `swgama`.`tbEstoque_tbBlusa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `swgama`.`tbEstoque_tbBlusa` ;

CREATE TABLE IF NOT EXISTS `swgama`.`tbEstoque_tbBlusa` (
  `idBlusaEstoque` INT NOT NULL,
  `idBlusa` INT NOT NULL,
  `idEstoque` INT NOT NULL,
  `qtd` INT NOT NULL,
  INDEX `fk_tbBlusa_has_tbEstoque_tbEstoque1_idx` (`idEstoque` ASC) ,
  INDEX `fk_tbBlusa_has_tbEstoque_tbBlusa1_idx` (`idBlusa` ASC) ,
  PRIMARY KEY (`idBlusaEstoque`),
  CONSTRAINT `fk_tbBlusa_has_tbEstoque_tbBlusa1`
    FOREIGN KEY (`idBlusa`)
    REFERENCES `swgama`.`tbBlusa` (`idBlusa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbBlusa_has_tbEstoque_tbEstoque1`
    FOREIGN KEY (`idEstoque`)
    REFERENCES `swgama`.`tbEstoque` (`idEstoque`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `swgama`.`tbEntradaInsumo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `swgama`.`tbEntradaInsumo` ;

CREATE TABLE IF NOT EXISTS `swgama`.`tbEntradaInsumo` (
  `idEntradaInsumo` INT NOT NULL,
  `data` DATE NOT NULL,
  `idFornecedor` INT NULL,
  PRIMARY KEY (`idEntradaInsumo`),
  INDEX `fk_tbEntradaInsumo_tbFornecedor1_idx` (`idFornecedor` ASC) ,
  CONSTRAINT `fk_tbEntradaInsumo_tbFornecedor1`
    FOREIGN KEY (`idFornecedor`)
    REFERENCES `swgama`.`tbFornecedor` (`idFornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `swgama`.`tbEntradaInsumo_tbInsumo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `swgama`.`tbEntradaInsumo_tbInsumo` ;

CREATE TABLE IF NOT EXISTS `swgama`.`tbEntradaInsumo_tbInsumo` (
  `idEntrada` INT NOT NULL,
  `idInsumo` INT NOT NULL,
  `valor` DOUBLE NULL,
  `qtd` DOUBLE NOT NULL,
  PRIMARY KEY (`idEntrada`, `idInsumo`),
  INDEX `fk_tbEntradaInsumo_has_tbInsumo_tbInsumo1_idx` (`idInsumo` ASC) ,
  INDEX `fk_tbEntradaInsumo_has_tbInsumo_tbEntradaInsumo1_idx` (`idEntrada` ASC) ,
  CONSTRAINT `fk_tbEntradaInsumo_has_tbInsumo_tbEntradaInsumo1`
    FOREIGN KEY (`idEntrada`)
    REFERENCES `swgama`.`tbEntradaInsumo` (`idEntradaInsumo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbEntradaInsumo_has_tbInsumo_tbInsumo1`
    FOREIGN KEY (`idInsumo`)
    REFERENCES `swgama`.`tbInsumo` (`idInsumo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `swgama`.`tbEntradaDespesa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `swgama`.`tbEntradaDespesa` ;

CREATE TABLE IF NOT EXISTS `swgama`.`tbEntradaDespesa` (
  `idEntradaDespesa` INT NOT NULL,
  `data` DATE NOT NULL,
  PRIMARY KEY (`idEntradaDespesa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `swgama`.`tbEntradaDespesa_tbDespesa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `swgama`.`tbEntradaDespesa_tbDespesa` ;

CREATE TABLE IF NOT EXISTS `swgama`.`tbEntradaDespesa_tbDespesa` (
  `idEntrada` INT NOT NULL,
  `idDespesa` INT NOT NULL,
  `valor` DOUBLE NULL,
  `qtd` DOUBLE NOT NULL,
  INDEX `fk_tbEntradaDespesa_has_tbDespesa_tbDespesa1_idx` (`idDespesa` ASC) ,
  INDEX `fk_tbEntradaDespesa_has_tbDespesa_tbEntradaDespesa1_idx` (`idEntrada` ASC) ,
  PRIMARY KEY (`idEntrada`, `idDespesa`),
  CONSTRAINT `fk_tbEntradaDespesa_has_tbDespesa_tbEntradaDespesa1`
    FOREIGN KEY (`idEntrada`)
    REFERENCES `swgama`.`tbEntradaDespesa` (`idEntradaDespesa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbEntradaDespesa_has_tbDespesa_tbDespesa1`
    FOREIGN KEY (`idDespesa`)
    REFERENCES `swgama`.`tbDespesa` (`idDespesa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

=


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

CREATE TABLE IF NOT EXISTS `swgama`.`tbUsuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(200) NOT NULL,
  `email` VARCHAR(200) NOT NULL,
  `senha` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;